/**
 * Standardized error codes used across the platform.
 * From doc 08 API Structure.
 */
export const ErrorCodes = {
  // Auth
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_FIELD: 'MISSING_FIELD',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // Business logic
  DUPLICATE_APPLICATION: 'DUPLICATE_APPLICATION',
  JOB_CLOSED: 'JOB_CLOSED',
  BOOKING_NOT_ACTIVE: 'BOOKING_NOT_ACTIVE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  INVALID_BOOKING_OTP: 'INVALID_BOOKING_OTP',
  BOOKING_OTP_EXPIRED: 'BOOKING_OTP_EXPIRED',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
